# Dataset 
train_data : "train_data.json"
val_data : "val_data.json"
image_size : 384 

# Model 
pretrained_model : 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'


# size of Vit model 

vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 32
init_lr: 1e-5





# generation configs
max_length: 20  
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5






# Extras 
seed: 42
