# Dataset 
train_data : "train_data.json"
val_data : "val_data.json"
image_size : 384 

# # Model 

pretrained : "https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_14M.pth"


# size of Vit model 

vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 32
init_lr: 1e-5





# generation configs
max_length: 20  
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10






# Extras 
seed: 42
early_stopping_patience : 3
